// Generated by gencpp from file coffeemachine/Check_Qtty.msg
// DO NOT EDIT!


#ifndef COFFEEMACHINE_MESSAGE_CHECK_QTTY_H
#define COFFEEMACHINE_MESSAGE_CHECK_QTTY_H

#include <ros/service_traits.h>


#include <coffeemachine/Check_QttyRequest.h>
#include <coffeemachine/Check_QttyResponse.h>


namespace coffeemachine
{

struct Check_Qtty
{

typedef Check_QttyRequest Request;
typedef Check_QttyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Check_Qtty
} // namespace coffeemachine


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::coffeemachine::Check_Qtty > {
  static const char* value()
  {
    return "c0572ee26a5f83fa67fcff4e56c1ca00";
  }

  static const char* value(const ::coffeemachine::Check_Qtty&) { return value(); }
};

template<>
struct DataType< ::coffeemachine::Check_Qtty > {
  static const char* value()
  {
    return "coffeemachine/Check_Qtty";
  }

  static const char* value(const ::coffeemachine::Check_Qtty&) { return value(); }
};


// service_traits::MD5Sum< ::coffeemachine::Check_QttyRequest> should match
// service_traits::MD5Sum< ::coffeemachine::Check_Qtty >
template<>
struct MD5Sum< ::coffeemachine::Check_QttyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::coffeemachine::Check_Qtty >::value();
  }
  static const char* value(const ::coffeemachine::Check_QttyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::coffeemachine::Check_QttyRequest> should match
// service_traits::DataType< ::coffeemachine::Check_Qtty >
template<>
struct DataType< ::coffeemachine::Check_QttyRequest>
{
  static const char* value()
  {
    return DataType< ::coffeemachine::Check_Qtty >::value();
  }
  static const char* value(const ::coffeemachine::Check_QttyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::coffeemachine::Check_QttyResponse> should match
// service_traits::MD5Sum< ::coffeemachine::Check_Qtty >
template<>
struct MD5Sum< ::coffeemachine::Check_QttyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::coffeemachine::Check_Qtty >::value();
  }
  static const char* value(const ::coffeemachine::Check_QttyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::coffeemachine::Check_QttyResponse> should match
// service_traits::DataType< ::coffeemachine::Check_Qtty >
template<>
struct DataType< ::coffeemachine::Check_QttyResponse>
{
  static const char* value()
  {
    return DataType< ::coffeemachine::Check_Qtty >::value();
  }
  static const char* value(const ::coffeemachine::Check_QttyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COFFEEMACHINE_MESSAGE_CHECK_QTTY_H
