// Generated by gencpp from file coffeemachine/Check_QttyResponse.msg
// DO NOT EDIT!


#ifndef COFFEEMACHINE_MESSAGE_CHECK_QTTYRESPONSE_H
#define COFFEEMACHINE_MESSAGE_CHECK_QTTYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace coffeemachine
{
template <class ContainerAllocator>
struct Check_QttyResponse_
{
  typedef Check_QttyResponse_<ContainerAllocator> Type;

  Check_QttyResponse_()
    : quantity()  {
    }
  Check_QttyResponse_(const ContainerAllocator& _alloc)
    : quantity(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _quantity_type;
  _quantity_type quantity;





  typedef boost::shared_ptr< ::coffeemachine::Check_QttyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coffeemachine::Check_QttyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Check_QttyResponse_

typedef ::coffeemachine::Check_QttyResponse_<std::allocator<void> > Check_QttyResponse;

typedef boost::shared_ptr< ::coffeemachine::Check_QttyResponse > Check_QttyResponsePtr;
typedef boost::shared_ptr< ::coffeemachine::Check_QttyResponse const> Check_QttyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coffeemachine::Check_QttyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coffeemachine::Check_QttyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::coffeemachine::Check_QttyResponse_<ContainerAllocator1> & lhs, const ::coffeemachine::Check_QttyResponse_<ContainerAllocator2> & rhs)
{
  return lhs.quantity == rhs.quantity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::coffeemachine::Check_QttyResponse_<ContainerAllocator1> & lhs, const ::coffeemachine::Check_QttyResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace coffeemachine

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::coffeemachine::Check_QttyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coffeemachine::Check_QttyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coffeemachine::Check_QttyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coffeemachine::Check_QttyResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coffeemachine::Check_QttyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coffeemachine::Check_QttyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coffeemachine::Check_QttyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ba18e1feb537f78454848d17fe57641";
  }

  static const char* value(const ::coffeemachine::Check_QttyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ba18e1feb537f78ULL;
  static const uint64_t static_value2 = 0x454848d17fe57641ULL;
};

template<class ContainerAllocator>
struct DataType< ::coffeemachine::Check_QttyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coffeemachine/Check_QttyResponse";
  }

  static const char* value(const ::coffeemachine::Check_QttyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coffeemachine::Check_QttyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string quantity\n"
"\n"
"\n"
;
  }

  static const char* value(const ::coffeemachine::Check_QttyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coffeemachine::Check_QttyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.quantity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Check_QttyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coffeemachine::Check_QttyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coffeemachine::Check_QttyResponse_<ContainerAllocator>& v)
  {
    s << indent << "quantity: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.quantity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COFFEEMACHINE_MESSAGE_CHECK_QTTYRESPONSE_H
